export const TopicList = [
  { code: "ADO", title: "Worship" },
  { code: "ADV", title: "Advent of the Lord" },
  { code: "ALB", title: "Praise" },
  { code: "AMA", title: "Dawn" },
  { code: "AMO", title: "Love" },
  { code: "ANN", title: "New Year" },
  { code: "BAU", title: "Baptism" },
  { code: "BNV", title: "Welcoming" },
  { code: "COM", title: "Communion" },
  { code: "CNF", title: "Trust" },
  { code: "CNG", title: "Consecration" },
  { code: "DES", title: "Farewell" },
  { code: "DUE", title: "Rest in the Lord" },
  { code: "ELE", title: "Election" },
  { code: "ESP", title: "Hope" },
  { code: "EVA", title: "Evangelization" },
  { code: "EXH", title: "Exhortation" },
  { code: "GLO", title: "Glory" },
  { code: "GOZ", title: "Joy" },
  { code: "GRC", title: "Grace" },
  { code: "GRT", title: "Gratitud" },
  { code: "HON", title: "Honor" },
  { code: "ING", title: "Inauguration" },
  { code: "INT", title: "Intercession" },
  { code: "INV", title: "Invitation" },
  { code: "JUV", title: "Youth" },
  { code: "LIB", title: "Liberality" },
  { code: "LCH", title: "Battle" },
  { code: "MAT", title: "Marriage" },
  { code: "OBR", title: "Labor" },
  { code: "ORA", title: "Prayer" },
  { code: "OAP", title: "Apostolic Prayer" },
  { code: "PAS", title: "Passion" },
  { code: "PET", title: "Petition" },
  { code: "RST", title: "Restoration" },
  { code: "RSU", title: "Resurrection" },
  { code: "SNC", title: "Holy Supper" },
] as const;

const TopicCodes = TopicList.map(topic=> topic.code);

export default TopicCodes;
